// Generated by scripts/sync_provisional_maturation.py. Do not edit.
export const MATURATION_POLICY = {
  "schema": "BOS_PROVISIONAL_MATURATION_POLICY_V1",
  "version": "1.0.0",
  "automatic_assessment": true,
  "automatic_metadata_persistence": true,
  "automatic_business_mutation": false,
  "release_checkpoints": [
    "BETA",
    "FINAL"
  ],
  "phases": [
    {
      "id": "foundations",
      "requires": [
        "binding_current",
        "context_present"
      ],
      "next_action": "Reconcile current project context and implement the next scoped workflow."
    },
    {
      "id": "build",
      "requires": [
        "source_readback"
      ],
      "next_action": "Complete the next scoped workflow and collect verification evidence."
    },
    {
      "id": "stabilise",
      "requires": [
        "workflows_implemented"
      ],
      "next_action": "Verify critical workflows, resolve defects and complete release obligations."
    },
    {
      "id": "release",
      "requires": [
        "verification_passed",
        "critical_blockers_clear"
      ],
      "next_action": "Present the pending beta or final-release decision to the owner."
    },
    {
      "id": "operate",
      "requires": [
        "release_approved",
        "release_receipt"
      ],
      "next_action": "Monitor verified operation and assess changes against the approved release."
    }
  ],
  "evidence_rule": "Fresh project-bound evidence only. Host-reported observations remain provisional; owner acceptance and release authorization are separate.",
  "persistence_rule": "Declared app state owner only; compare current revision, preserve history, read back exact output.",
  "display_rule": "Show assessed phase, verification, pending obligations and owner decision; no maturity percentage."
};
