// Generated by scripts/generate_ai_execution_footer.py. Do not edit.
const NEXT_STEP_EXECUTION_ADVISORY = Object.freeze({
  "schema": "BOS_NEXT_STEP_EXECUTION_GUIDANCE_V1",
  "version": "1.1.0",
  "emission": "MANDATORY_SUBSTANTIVE_GOVERNED_RESPONSE_FOOTER",
  "automatic_model_switching": false,
  "grants_authority": false,
  "instruction": "At the end of each substantive governed response recommend model and reasoning for the actual next task. Use one self row in a direct chat; use separate orchestrator and target rows for an actual handoff to another chat or native builder. Classify each task independently. An external coding agent editing a remote sandbox is still the executor. If no next task is identified, say not applicable; do not invent work.",
  "selection": "Prefer the least expensive available model with adequate capability and the shallowest safe effort. Preserve explicit user choices. Exact model names, native Auto and effort labels require current account-visible evidence bound to host, project and chat. Refresh after a context switch or at least hourly. Otherwise recommend a capability and desired effort, with actual control UNKNOWN. Availability does not prove active settings.",
  "format": "Next [self/orchestrator/target] \u2014 host (project/chat): model or capability / supported reasoning or UNKNOWN (desired effort) \u2014 brief next-task reason. Recommendation only.",
  "task_effort": {
    "deterministic_checks": "NONE",
    "verified_repetitive_transformation": "LOW",
    "routine_implementation": "MEDIUM",
    "debugging_architecture_or_high_risk": "HIGH",
    "ambiguous_consequential_decision": "MAXIMUM"
  },
  "host_rules": {
    "CODEX": "Use current host model catalog and per-model effort options. Emitted slash commands do not apply settings.",
    "CLAUDE_CODE": "Use current account model catalog and model-specific supported effort labels; do not translate Codex labels blindly.",
    "BASE44": "Use native Auto or exact model only when available in the current Build selector. Discuss uses its own platform-managed model. Separate reasoning remains UNKNOWN unless the current host verifies that control.",
    "REPLIT": "Use current account-visible Agent model, Auto, mode and effort controls. Advice does not activate the deferred Replit Cloud BOS adapter.",
    "OTHER": "Recommend capability and desired effort; exact controls remain UNKNOWN until verified."
  },
  "privacy": "Evaluate task and host settings locally. This guidance adds no raw-prompt input, credential collection or cloud persistence. It does not grant capability entitlement, replace project activation or attest host emission.",
  "response_validation": {
    "validator": "ai_execution_next_step.validate_footer",
    "requires": [
      "role",
      "host",
      "project/chat",
      "model_or_capability",
      "reasoning_or_unknown_with_desired_effort",
      "next_task_reason",
      "recommendation_only"
    ],
    "actual_settings_required": true,
    "actual_format": "Actual model/reasoning: <observed model or UNKNOWN> / <observed effort or UNKNOWN>",
    "exact_models": "Regenerate a current recommendation from project/session/request/source-bound input; host-reported catalogs are not active-setting proof.",
    "workflow": "Visible formatting is separate from actual-guidance, applicable-rule and artifact readback evidence.",
    "structured_output": "Preserve machine-readable output and report unsupported native enforcement.",
    "correction_limit": 1
  }
});
const NEXT_STEP_TASK_RULES = {
  "DETERMINISTIC_VALIDATION": {
    "capability": "NO_MODEL",
    "reasoning": "NONE"
  },
  "VERIFIED_TRANSFORMATION": {
    "capability": "FAST_STRUCTURED",
    "reasoning": "LOW"
  },
  "ROUTINE_IMPLEMENTATION": {
    "capability": "CODING",
    "reasoning": "MEDIUM"
  },
  "DEBUG_RECONCILE": {
    "capability": "FRONTIER_CODING",
    "reasoning": "HIGH"
  },
  "ARCHITECTURE_GOVERNANCE": {
    "capability": "DEEP_REASONING",
    "reasoning": "HIGH"
  },
  "HIGH_RISK_MUTATION": {
    "capability": "FRONTIER_CODING",
    "reasoning": "HIGH"
  },
  "AMBIGUOUS_DECISION": {
    "capability": "DEEP_REASONING",
    "reasoning": "MAXIMUM"
  },
  "PLATFORM_NATIVE_EXECUTION": {
    "capability": "PLATFORM_STRONGEST_AVAILABLE",
    "reasoning": "HIGH"
  }
};
const NEXT_STEP_RESPONSE_SCHEMA = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "BOS AI execution next step V1",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "schema": {
      "const": "BOS_AI_EXECUTION_NEXT_STEP_V1"
    },
    "version": {
      "const": "1.0.0"
    },
    "mode": {
      "enum": [
        "SINGLE",
        "DUPLEX",
        "NO_NEXT_TASK"
      ]
    },
    "automatic_model_switching": {
      "const": false
    },
    "recommendations": {
      "type": "array",
      "maxItems": 2,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "host": {
            "type": "string",
            "minLength": 1
          },
          "project_ref": {
            "type": "string",
            "minLength": 1
          },
          "chat_ref": {
            "type": "string",
            "minLength": 1
          },
          "execution_route": {
            "type": "string",
            "minLength": 1
          },
          "task": {
            "type": "string",
            "minLength": 3
          },
          "task_class": {
            "type": "string",
            "minLength": 1
          },
          "capability": {
            "type": "string",
            "minLength": 1
          },
          "requested_effort": {
            "enum": [
              "NONE",
              "LOW",
              "MEDIUM",
              "HIGH",
              "MAXIMUM"
            ]
          },
          "model": {
            "type": "string",
            "minLength": 1
          },
          "reasoning": {
            "type": "string",
            "minLength": 1
          },
          "reason": {
            "type": "string",
            "minLength": 1
          },
          "role": {
            "enum": [
              "SELF",
              "ORCHESTRATOR",
              "TARGET"
            ]
          },
          "catalog_status": {
            "enum": [
              "CURRENT",
              "UNKNOWN_OR_STALE"
            ]
          },
          "selection_status": {
            "enum": [
              "CAPABILITY_ONLY",
              "NOT_REQUIRED",
              "HOST_MANAGED",
              "USER_CHOICE_UNVERIFIED",
              "USER_CHOICE",
              "SUPPORTED_RECOMMENDATION"
            ]
          },
          "settings_status": {
            "const": "RECOMMENDATION_ONLY"
          }
        },
        "required": [
          "host",
          "project_ref",
          "chat_ref",
          "execution_route",
          "task",
          "task_class",
          "capability",
          "requested_effort",
          "model",
          "reasoning",
          "reason",
          "role",
          "catalog_status",
          "selection_status",
          "settings_status"
        ]
      }
    }
  },
  "required": [
    "schema",
    "version",
    "mode",
    "automatic_model_switching",
    "recommendations"
  ],
  "allOf": [
    {
      "if": {
        "properties": {
          "mode": {
            "const": "NO_NEXT_TASK"
          }
        }
      },
      "then": {
        "properties": {
          "recommendations": {
            "minItems": 0,
            "maxItems": 0
          }
        }
      }
    },
    {
      "if": {
        "properties": {
          "mode": {
            "const": "SINGLE"
          }
        }
      },
      "then": {
        "properties": {
          "recommendations": {
            "minItems": 1,
            "maxItems": 1,
            "prefixItems": [
              {
                "properties": {
                  "role": {
                    "const": "SELF"
                  }
                }
              }
            ]
          }
        }
      }
    },
    {
      "if": {
        "properties": {
          "mode": {
            "const": "DUPLEX"
          }
        }
      },
      "then": {
        "properties": {
          "recommendations": {
            "minItems": 2,
            "maxItems": 2,
            "prefixItems": [
              {
                "properties": {
                  "role": {
                    "const": "ORCHESTRATOR"
                  }
                }
              },
              {
                "properties": {
                  "role": {
                    "const": "TARGET"
                  },
                  "execution_route": {
                    "enum": [
                      "OTHER_CHAT",
                      "NATIVE_BUILDER"
                    ]
                  }
                }
              }
            ]
          }
        }
      }
    }
  ]
};

function nextTaskClass(signals = {}) {
  if (signals.task_class && signals.task_class !== 'PLATFORM_NATIVE_EXECUTION') return signals.task_class;
  if (signals.architecture || signals.governance_redesign) return 'ARCHITECTURE_GOVERNANCE';
  if (signals.ambiguous && signals.consequential) return 'AMBIGUOUS_DECISION';
  if (['security','privacy','billing','permissions','schema_mutation'].some(k => signals[k])) return 'HIGH_RISK_MUTATION';
  if (signals.debugging || signals.reconciliation) return 'DEBUG_RECONCILE';
  if (signals.deterministic_only) return 'DETERMINISTIC_VALIDATION';
  if (signals.repetitive && signals.verified_transform) return 'VERIFIED_TRANSFORMATION';
  return 'ROUTINE_IMPLEMENTATION';
}
// Advisory consistency only. The host must supply actual native/source readback.
function validateNextStepResponse({ message, result, scopes = [], now = Date.now() } = {}) {
  const errors = [];
  const text = typeof message === 'string' ? message.trim() : '';
  if (result?.schema !== 'BOS_AI_EXECUTION_NEXT_STEP_V1' || result?.automatic_model_switching !== false
      || !Array.isArray(result?.recommendations)) return ['NEXT_STEP_RECORD_INVALID'];
  const rows = result.recommendations;
  const roles = result.mode === 'SINGLE' ? ['SELF'] : result.mode === 'DUPLEX' ? ['ORCHESTRATOR','TARGET'] : result.mode === 'NO_NEXT_TASK' ? [] : null;
  if (!roles || rows.length !== roles.length) return ['NEXT_STEP_ROLES_INVALID'];
  if (!rows.length && scopes.length) return ['NEXT_TASK_CONTRADICTS_CURRENT_ADVISORY'];
  if (!rows.length) return text.endsWith('Next model/reasoning: not applicable — no next task identified.') ? [] : ['NEXT_STEP_FOOTER_MISSING'];
  const required = NEXT_STEP_RESPONSE_SCHEMA.properties.recommendations.items.required;
  const footer = [];
  for (const [i, row] of rows.entries()) {
    if (required.some(k => typeof row?.[k] !== 'string' || !row[k].trim()) || row.role !== roles[i]
        || row.settings_status !== 'RECOMMENDATION_ONLY') { errors.push('NEXT_STEP_FIELDS_INVALID'); continue; }
    const scope = scopes[i];
    if (!scope || ['host','project_ref','chat_ref','execution_route','task'].some(k => scope[k] !== row[k])) errors.push('NEXT_STEP_SCOPE_MISMATCH');
    const taskClass = nextTaskClass(scope?.signals);
    const rule = NEXT_STEP_TASK_RULES[taskClass];
    if (!rule || row.task_class !== taskClass || row.capability !== rule.capability
        || row.requested_effort !== rule.reasoning) errors.push('NEXT_STEP_POLICY_MISMATCH');
    if (row.task.trim().split(/\s+/).length < 2) errors.push('NEXT_TASK_REASON_MISSING');
    if (!['CAPABILITY_ONLY','NOT_REQUIRED','HOST_MANAGED','USER_CHOICE_UNVERIFIED','USER_CHOICE','SUPPORTED_RECOMMENDATION'].includes(row.selection_status)) errors.push('SELECTION_STATUS_INVALID');
    if (row.role === 'TARGET' && !['OTHER_CHAT','NATIVE_BUILDER'].includes(row.execution_route)) errors.push('NEXT_STEP_HANDOFF_INVALID');
    if (!['NONE','LOW','MEDIUM','HIGH','MAXIMUM'].includes(row.requested_effort)) errors.push('DESIRED_EFFORT_INVALID');
    if (row.selection_status === 'CAPABILITY_ONLY') {
      if (row.model !== row.capability || row.reasoning !== 'UNKNOWN') errors.push('CAPABILITY_CONTROL_UNVERIFIED');
    } else if (row.selection_status === 'NOT_REQUIRED') {
      if (row.model !== 'NO_MODEL' || row.reasoning !== 'NOT_APPLICABLE') errors.push('NO_MODEL_REASONING_INVALID');
    } else if (row.selection_status === 'HOST_MANAGED' && row.host === 'BASE44' && scope?.mode === 'DISCUSS' && row.execution_route === 'NATIVE_BUILDER') {
      if (row.model !== 'PLATFORM_MANAGED' || row.reasoning !== 'UNKNOWN') errors.push('BASE44_DISCUSS_MANAGED');
    } else {
      const catalog = scope?.catalog;
      const age = now - Date.parse(catalog?.observed_at);
      const current = catalog?.evidence_ref && age >= 0 && age <= 3600000
        && ['host','project_ref','chat_ref','account_ref'].every(k => scope?.[k] && catalog[k] === scope[k]);
      const model = current && catalog.models?.find(m => m.id === row.model);
      const effortOK = row.reasoning === 'UNKNOWN' || model?.reasoning_levels?.includes(row.reasoning)
        || model?.reasoning_control === row.reasoning;
      const unverifiedChoice = row.selection_status === 'USER_CHOICE_UNVERIFIED'
        && scope?.user_choice?.model === row.model && row.reasoning === 'UNKNOWN';
      if ((!model || !effortOK) && !unverifiedChoice) errors.push('MODEL_OR_EFFORT_UNVERIFIED');
      if (model && !scope?.user_choice?.model && !model.capabilities?.includes(row.capability)) errors.push('MODEL_CAPABILITY_UNSUPPORTED');
      const requested = scope?.user_choice?.reasoning ?? model?.effort_mapping?.[row.requested_effort];
      const expectedEffort = model?.reasoning_levels?.includes(requested) ? requested
        : ['HOST_MANAGED','NOT_SUPPORTED'].includes(model?.reasoning_control) ? model.reasoning_control : 'UNKNOWN';
      if (row.reasoning !== expectedEffort) errors.push('REASONING_POLICY_MISMATCH');
    }
    if (scope?.user_choice?.model && scope.user_choice.model !== row.model) errors.push('USER_CHOICE_NOT_PRESERVED');
    let line = `Next ${row.role.toLowerCase()} — ${row.host} (${row.project_ref}/${row.chat_ref}): ${row.model} / ${row.reasoning}`;
    if (row.reasoning === 'UNKNOWN') line += ` (desired ${row.requested_effort})`;
    line += ` — ${row.task}.`;
    if (row.selection_status.startsWith('USER_CHOICE') || row.reason.includes('do not substitute')) line += ` ${row.reason}`;
    footer.push(line + ' Recommendation only.');
  }
  if (!text.endsWith(footer.join('\n'))) errors.push('NEXT_STEP_RENDER_MISMATCH');
  return [...new Set(errors)];
}

module.exports = { NEXT_STEP_EXECUTION_ADVISORY, NEXT_STEP_RESPONSE_SCHEMA, validateNextStepResponse };
